### PR TITLE
#29 - out_transitions for location with no transitions

### LINKED ISSUE #29: out_transitions for location with no transitions
Here is a small example of an automaton where the second location has no outgoing transition.
```julia
using HybridSystems

automaton = LightAutomaton(2)
add_transition!(automaton, 1, 1, 1)
add_transition!(automaton, 1, 2, 2)
m1 = "mode1"
m2 = "mode2"
modes = [m1, m2]
resetmaps = ["transition1", "transition2"]
switchings = [AutonomousSwitching() for _ in 1:2]
H = HybridSystem(automaton, modes, resetmaps, switchings)

println("outgoing transitions of location 1:")
out_transitions(H, 1)
println("outgoing transitions of location 2:")
out_transitions(H, 2)
```
This script breaks in the last line with the following message:
```
ERROR: LoadError: AssertionError: 1 <= r <= nstates(A)
```
After adding `println("q = $q, r = $r")` to [this line](https://github.com/blegat/HybridSystems.jl/blob/06b6f8050555e5f001c93bf3f0200a7fa5db12a7/src/light.jl#L111) I get this output:
```
q = 1, r = 1
q = 1, r = 2
outgoing transitions of location 1:
q = 1, r = 1
outgoing transitions of location 2:
q = 2, r = 0
ERROR: LoadError: AssertionError: 1 <= r <= nstates(A)
```
It seems that the graph method [here](https://github.com/blegat/HybridSystems.jl/blob/06b6f8050555e5f001c93bf3f0200a7fa5db12a7/src/light.jl#L175) returns `0` if there is no outgoing edge, which is apparently not expected by the other function.

### PR DESCRIPTION
**Pull request by schillic**
This is one attempt to close #29.
This workaround is not very elegant due to the restriction that I want to make the code type stable. Note that it relies on `LightGraphs` to return an empty list for non-existing nodes. I understand if you do not accept this workaround.

### CODE REVIEW

**Comment by schillic** [comment]
Sorry, I do not see how to incorporate the type in the proper way :disappointed:

**Comment by mforets** [comment]
How about:

```
$ git diff
diff --git a/src/light.jl b/src/light.jl
index 42859d3..b729e37 100644
--- a/src/light.jl
+++ b/src/light.jl
@@ -171,7 +171,7 @@ function in_transitions(A::LightAutomaton, s)
     LightTransitionIterator(A, edges)

 end
 function out_transitions(A::LightAutomaton, s)
-    edges = MappedArrays.mappedarray(dst -> edge_object(A, s, dst),
+    edges = MappedArrays.mappedarray(Int, dst -> edge_object(A, s, dst),
                                      LightGraphs.outneighbors(A.G, s))
     LightTransitionIterator(A, edges)
 end
```

Then:

```julia
julia> out_transitions(H, 2)
LightTransitionIterator{SimpleDiGraph{Int64},LightGraphs.SimpleGraphs.SimpleEdge{Int64},MappedArrays.MultiMappedArray{Int64,1,Tuple{Arra
y{Int64,1}},Type{Int64},getfield(Main, Symbol("##5#6")){LightAutomaton{SimpleDiGraph{Int64},LightGraphs.SimpleGraphs.SimpleEdge{Int64}},
Int64}}}(LightAutomaton{SimpleDiGraph{Int64},LightGraphs.SimpleGraphs.SimpleEdge{Int64}}({2, 2} directed simple Int64 graph, Dict(Edge 1
 => 1=>Dict(1=>1),Edge 1 => 2=>Dict(2=>2)), 2, 2), Int64[])

julia> isempty(out_transitions(H, s))
true
```

> Sorry, I do not see how to incorporate the type in the proper way

The types of source and dest are always `Int`'s (see [this line](https://github.com/blegat/HybridSystems.jl/blob/master/src/light.jl#L17)).

**Comment by schillic** [comment]
I also tried that, but the result differs from the previous one in `master` (`ReadonlyMappedArray` vs. `MultiMappedArray`). See [this example](https://github.com/blegat/HybridSystems.jl/issues/29#issue-412088333) with a `println(out_transitions(H, 1))`.
in `master`:
```julia
HybridSystems.LightTransitionIterator{
    LightGraphs.SimpleGraphs.SimpleDiGraph{Int64},
    LightGraphs.SimpleGraphs.SimpleEdge{Int64},
    MappedArrays.ReadonlyMappedArray{
        LightGraphs.SimpleGraphs.SimpleEdge{Int64},1,Array{Int64,1},
        getfield(HybridSystems, Symbol("##21#22")){LightAutomaton{
            LightGraphs.SimpleGraphs.SimpleDiGraph{Int64},
            LightGraphs.SimpleGraphs.SimpleEdge{Int64}},Int64}
    }
}(LightAutomaton{LightGraphs.SimpleGraphs.SimpleDiGraph{Int64},
                 LightGraphs.SimpleGraphs.SimpleEdge{Int64}}
    ({2, 2} directed simple Int64 graph,
     Dict(Edge 1 => 2=>Dict(2=>2),Edge 1 => 1=>Dict(1=>1)), 2, 2),
  LightGraphs.SimpleGraphs.SimpleEdge{Int64}[Edge 1 => 1, Edge 1 => 2])
```
using `Int`:
```julia
HybridSystems.LightTransitionIterator{
    LightGraphs.SimpleGraphs.SimpleDiGraph{Int64},
    LightGraphs.SimpleGraphs.SimpleEdge{Int64},
    MappedArrays.MultiMappedArray{
        Int64,1,Tuple{Array{Int64,1}},Type{Int64},
        getfield(HybridSystems, Symbol("##25#26")){
            LightAutomaton{LightGraphs.SimpleGraphs.SimpleDiGraph{Int64},
            LightGraphs.SimpleGraphs.SimpleEdge{Int64}},Int64}
    }
}(LightAutomaton{LightGraphs.SimpleGraphs.SimpleDiGraph{Int64},
                 LightGraphs.SimpleGraphs.SimpleEdge{Int64}}
    ({2, 2} directed simple Int64 graph,
     Dict(Edge 1 => 2=>Dict(2=>2),Edge 1 => 1=>Dict(1=>1)), 2, 2), [1, 2])
```

**Comment by schillic** [comment]
> The types of source and dest are always Int's (see this line).

True, but the expected type for `MappedArrays` is the *result* type of the mapping, which should be the "edge type". See [here](https://github.com/JuliaArrays/MappedArrays.jl/blob/a8189572df9ca2db3d28fd74d1684c24c1d56c26/src/MappedArrays.jl#L61): `T` is the type *after* applying the function.

File: src/light.jl [hunk 1]
```diff
@@ -165,13 +166,15 @@ source(::LightAutomaton, t::LightTransition) = t.edge.src
 event(A::LightAutomaton, t::LightTransition) = A.Σ[t.edge][t.id]
 target(::LightAutomaton, t::LightTransition) = t.edge.dst
 
-function in_transitions(A::LightAutomaton, s)
-    edges = MappedArrays.mappedarray(src -> edge_object(A, src, s),
+function in_transitions(A::LightAutomaton{GT, ET}, s) where {GT, ET}
+    edges = MappedArrays.mappedarray(ET,
```
Comment (blegat) [inline src/light.jl]: I misinterpreted the first argument, sorry. If you give 3 arguments to `mappedarray`, the first one is `f`, the second is the inverse of `f` (used in `setindex!`) and the third one is the array to map.
When the first argument is a type, then it is used as the return type and it does not try a testvalue of zero to try to guess the type (which is what we want).
However, here the function we want to apply is not a type so it does not work. I suggest we just bypass the `mappedarray` function and directly do
```julia
f(src) = edge_object(A, src, s)
inneigh = LightGraphs.inneighbors(A.G, s)
edges = MappedArrays.ReadonlyMappedArray{ET, 1, typeof(f), typeof(inneigh)}(f, inneigh)
```

Comment (schillic) [reply src/light.jl]: Thanks, I'll try.

Comment (schillic) [reply src/light.jl]: Should it not be the other way around (swap type parameters 3 and 4)? See [here](https://github.com/JuliaArrays/MappedArrays.jl/blob/a8189572df9ca2db3d28fd74d1684c24c1d56c26/src/MappedArrays.jl#L10).

Comment (blegat) [reply src/light.jl]: Yes indeed!
